# Generated by Django 3.1 on 2021-07-30 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(choices=[('Director', 'Director'), ('Manager', 'Manager'), ('Technician', 'Technician'), ('Clerk', 'Clerk'), ('Accountant', 'Accountant')], max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Binary', 'Binary')], max_length=50)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Full-Time', 'Full-Time')], max_length=50)),
                ('postal_code', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('county_or_state_or_region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('employment_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Binary', 'Binary')], max_length=50)),
                ('postal_code', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=200)),
                ('year', models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)])),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.farmer')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataapp.staff')),
            ],
        ),
    ]
