# Generated by Django 3.1 on 2021-07-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_auto_20210731_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='total_amount_owed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='billing',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
