# Generated by Django 3.1 on 2021-08-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0006_auto_20210804_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='year_of_payment',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2021),
        ),
    ]
