# Generated by Django 3.1 on 2021-08-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0007_billing_year_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='pay',
        ),
    ]
