# Generated by Django 3.1 on 2021-08-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0009_payfarmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='recorded_by',
        ),
    ]
