# Generated by Django 3.1 on 2021-08-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0010_remove_billing_recorded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='year_of_payment',
        ),
    ]
